"""baseline

Revision ID: aac138c38096
Revises:
Create Date: 2026-07-25 01:31:29.193236

Captures the full schema as it existed immediately before this project
adopted Alembic (production-hardening prompt 1) — i.e. everything
`Base.metadata.create_all()` had ever been relied on to build, up to but
not including `DiaryEntry.updated_at`/`MealPlanEntry.updated_at` (added
the same session Alembic was introduced; see the next revision,
`b2f1b0b0e001_add_diary_meal_plan_updated_at.py`, for why that one
column addition needed its own careful nullable→backfill→NOT NULL
migration rather than being folded into this baseline).

Generated by autogenerating against a genuinely empty database with
`app.models` at that exact prior commit (`git show
c104b08~1:backend/app/models.py`) — not hand-written, so it should be
trusted as an accurate snapshot rather than re-derived by reading model
definitions.

Two ways this runs, both correct:

- **Fresh database** (new deployment, CI, local dev bootstrap): plain
  `alembic upgrade head` executes this `upgrade()` for real, creating
  every table from nothing — the exact equivalent of what
  `create_all()` used to do on first boot.
- **Existing database** (anything that's already been running this app
  — including production): do **not** run this migration's `upgrade()`
  — the tables already exist. Instead run `alembic stamp aac138c38096`
  once to tell Alembic "this database is already at this point without
  actually running the DDL", then `alembic upgrade head` applies only
  what comes after. See `docs/migrations.md` for the exact commands.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac138c38096'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ix_foods_name_trgm below needs pg_trgm's gin_trgm_ops operator class
    # to exist before its CREATE INDEX runs — main.py used to create this
    # extension defensively on every startup (after create_all(), so a
    # genuinely first-ever boot would actually have hit this ordering bug
    # too), which is no longer the schema-creation path once migrations
    # own that job. A no-op on SQLite (used by the test suite), which has
    # no concept of extensions and where this index is declared without
    # the postgresql_using kwarg anyway.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('protein_g_per_100g', sa.Float(), nullable=False),
    sa.Column('amino_acids', sa.JSON(), nullable=False),
    sa.Column('digestibility_diaas', sa.JSON(), nullable=True),
    sa.Column('digestibility_diaas_source', sa.String(), nullable=True),
    sa.Column('digestibility_pdcaas', sa.Float(), nullable=True),
    sa.Column('digestibility_pdcaas_source', sa.String(), nullable=True),
    sa.Column('fdc_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('gtin_upc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_fdc_id'), 'foods', ['fdc_id'], unique=True)
    op.create_index(op.f('ix_foods_gtin_upc'), 'foods', ['gtin_upc'], unique=True)
    op.create_index('ix_foods_name_trgm', 'foods', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('is_lactating', sa.Boolean(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('dietary_pattern', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), server_default='free', nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_limit', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('requests_this_period', sa.Integer(), server_default='0', nullable=False),
    sa.Column('period_started_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('clinician_client_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinician_user_id', sa.Integer(), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinician_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinician_user_id', 'client_user_id', name='uq_clinician_client')
    )
    op.create_index(op.f('ix_clinician_client_links_client_user_id'), 'clinician_client_links', ['client_user_id'], unique=False)
    op.create_index(op.f('ix_clinician_client_links_clinician_user_id'), 'clinician_client_links', ['clinician_user_id'], unique=False)
    op.create_table('clinician_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinician_user_id', sa.Integer(), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinician_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinician_notes_client_user_id'), 'clinician_notes', ['client_user_id'], unique=False)
    op.create_index(op.f('ix_clinician_notes_clinician_user_id'), 'clinician_notes', ['clinician_user_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('food_nutrients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_key', sa.String(), nullable=False),
    sa.Column('amount_per_100g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'nutrient_key', name='uq_food_nutrient')
    )
    op.create_index(op.f('ix_food_nutrients_food_id'), 'food_nutrients', ['food_id'], unique=False)
    op.create_index('ix_food_nutrients_key_amount', 'food_nutrients', ['nutrient_key', 'amount_per_100g'], unique=False)
    op.create_table('food_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('package_price', sa.Float(), nullable=False),
    sa.Column('package_quantity_g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'food_id', name='uq_food_price_user_food')
    )
    op.create_index(op.f('ix_food_prices_food_id'), 'food_prices', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_prices_user_id'), 'food_prices', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_account_owner', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('is_lactating', sa.Boolean(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('dietary_pattern', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('import_slug', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_licence', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('content_fingerprint', sa.String(), nullable=True),
    sa.Column('stock_status', sa.String(), nullable=True),
    sa.Column('match_coverage_lines', sa.Float(), nullable=True),
    sa.Column('match_coverage_mass', sa.Float(), nullable=True),
    sa.Column('unresolved_ingredients', sa.JSON(), nullable=True),
    sa.Column('educational_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_import_slug'), 'recipes', ['import_slug'], unique=True)
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('collection_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('assignment_source', sa.String(), nullable=True),
    sa.Column('assignment_confidence', sa.Float(), nullable=True),
    sa.Column('assignment_reason', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(), server_default='approved', nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'recipe_id', name='uq_collection_recipe')
    )
    op.create_index(op.f('ix_collection_recipes_collection_id'), 'collection_recipes', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_recipes_recipe_id'), 'collection_recipes', ['recipe_id'], unique=False)
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('meal', sa.String(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('quantity_servings', sa.Float(), nullable=True),
    sa.CheckConstraint('(food_id IS NOT NULL AND quantity_g IS NOT NULL AND recipe_id IS NULL AND quantity_servings IS NULL) OR (recipe_id IS NOT NULL AND quantity_servings IS NOT NULL AND food_id IS NULL AND quantity_g IS NULL)', name='ck_diary_entry_exactly_one_of_food_or_recipe'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entries_entry_date'), 'diary_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_diary_entries_profile_id'), 'diary_entries', ['profile_id'], unique=False)
    op.create_index(op.f('ix_diary_entries_user_id'), 'diary_entries', ['user_id'], unique=False)
    op.create_table('diary_meal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_meal_templates_profile_id'), 'diary_meal_templates', ['profile_id'], unique=False)
    op.create_index(op.f('ix_diary_meal_templates_user_id'), 'diary_meal_templates', ['user_id'], unique=False)
    op.create_table('diary_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('drv_methodology_version', sa.String(), nullable=False),
    sa.Column('scoring_methodology_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'entry_date', name='uq_diary_snapshot_user_date')
    )
    op.create_index(op.f('ix_diary_snapshots_entry_date'), 'diary_snapshots', ['entry_date'], unique=False)
    op.create_index(op.f('ix_diary_snapshots_profile_id'), 'diary_snapshots', ['profile_id'], unique=False)
    op.create_index(op.f('ix_diary_snapshots_user_id'), 'diary_snapshots', ['user_id'], unique=False)
    op.create_table('dietary_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'category', 'tag', name='uq_dietary_constraint')
    )
    op.create_index(op.f('ix_dietary_constraints_profile_id'), 'dietary_constraints', ['profile_id'], unique=False)
    op.create_index(op.f('ix_dietary_constraints_user_id'), 'dietary_constraints', ['user_id'], unique=False)
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('meal', sa.String(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('quantity_servings', sa.Float(), nullable=True),
    sa.CheckConstraint('(food_id IS NOT NULL AND quantity_g IS NOT NULL AND recipe_id IS NULL AND quantity_servings IS NULL) OR (recipe_id IS NOT NULL AND quantity_servings IS NOT NULL AND food_id IS NULL AND quantity_g IS NULL)', name='ck_meal_plan_entry_exactly_one_of_food_or_recipe'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_entries_plan_date'), 'meal_plan_entries', ['plan_date'], unique=False)
    op.create_index(op.f('ix_meal_plan_entries_profile_id'), 'meal_plan_entries', ['profile_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_entries_user_id'), 'meal_plan_entries', ['user_id'], unique=False)
    op.create_table('meal_plan_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_templates_profile_id'), 'meal_plan_templates', ['profile_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_templates_user_id'), 'meal_plan_templates', ['user_id'], unique=False)
    op.create_table('medical_recommendation_acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_recommendation_acknowledgements_profile_id'), 'medical_recommendation_acknowledgements', ['profile_id'], unique=False)
    op.create_table('recipe_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_comments_recipe_id'), 'recipe_comments', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_comments_user_id'), 'recipe_comments', ['user_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('recipe_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'user_id', name='uq_recipe_rating')
    )
    op.create_index(op.f('ix_recipe_ratings_recipe_id'), 'recipe_ratings', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_ratings_user_id'), 'recipe_ratings', ['user_id'], unique=False)
    op.create_table('recipe_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'shared_with_user_id', name='uq_recipe_share')
    )
    op.create_index(op.f('ix_recipe_shares_recipe_id'), 'recipe_shares', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_shares_shared_with_user_id'), 'recipe_shares', ['shared_with_user_id'], unique=False)
    op.create_table('recipe_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'tag', name='uq_recipe_tag')
    )
    op.create_index(op.f('ix_recipe_tags_recipe_id'), 'recipe_tags', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_tags_tag'), 'recipe_tags', ['tag'], unique=False)
    op.create_table('robustness_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('simulation_count', sa.Integer(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('overall_explanation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robustness_results_recipe_id'), 'robustness_results', ['recipe_id'], unique=False)
    op.create_index('ix_robustness_results_recipe_id_is_latest', 'robustness_results', ['recipe_id', 'is_latest'], unique=False)
    op.create_index('uq_robustness_results_recipe_id_latest', 'robustness_results', ['recipe_id'], unique=True, postgresql_where=sa.text('is_latest'), sqlite_where=sa.text('is_latest'))
    op.create_table('saved_filter_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_filter_presets_profile_id'), 'saved_filter_presets', ['profile_id'], unique=False)
    op.create_index(op.f('ix_saved_filter_presets_user_id'), 'saved_filter_presets', ['user_id'], unique=False)
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'log_date', name='uq_weight_log_user_date')
    )
    op.create_index(op.f('ix_weight_logs_log_date'), 'weight_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_weight_logs_profile_id'), 'weight_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_weight_logs_user_id'), 'weight_logs', ['user_id'], unique=False)
    op.create_table('diary_meal_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('quantity_servings', sa.Float(), nullable=True),
    sa.CheckConstraint('(food_id IS NOT NULL AND quantity_g IS NOT NULL AND recipe_id IS NULL AND quantity_servings IS NULL) OR (recipe_id IS NOT NULL AND quantity_servings IS NOT NULL AND food_id IS NULL AND quantity_g IS NULL)', name='ck_diary_meal_template_item_exactly_one_of_food_or_recipe'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['diary_meal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_meal_template_items_template_id'), 'diary_meal_template_items', ['template_id'], unique=False)
    op.create_table('meal_plan_template_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('quantity_servings', sa.Float(), nullable=True),
    sa.CheckConstraint('(food_id IS NOT NULL AND quantity_g IS NOT NULL AND recipe_id IS NULL AND quantity_servings IS NULL) OR (recipe_id IS NOT NULL AND quantity_servings IS NOT NULL AND food_id IS NULL AND quantity_g IS NULL)', name='ck_meal_plan_template_entry_exactly_one_of_food_or_recipe'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['meal_plan_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_template_entries_template_id'), 'meal_plan_template_entries', ['template_id'], unique=False)
    op.create_table('recipe_ingredient_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('quantity_min', sa.Float(), nullable=True),
    sa.Column('quantity_max', sa.Float(), nullable=True),
    sa.Column('normalised_quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('prep_note', sa.String(), nullable=True),
    sa.Column('optional_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('parsing_confidence', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_relationship', sa.String(), nullable=True),
    sa.Column('match_rationale', sa.String(), nullable=True),
    sa.Column('match_preferred_fdc_id', sa.Integer(), nullable=True),
    sa.Column('match_preferred_food_id', sa.Integer(), nullable=True),
    sa.Column('match_used_fallback', sa.Boolean(), nullable=True),
    sa.Column('match_validation_warning', sa.String(), nullable=True),
    sa.Column('match_candidates', sa.JSON(), nullable=True),
    sa.Column('manually_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('conversion_assumptions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_ingredient_id'], ['recipe_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredient_provenance_recipe_ingredient_id'), 'recipe_ingredient_provenance', ['recipe_ingredient_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredient_provenance_recipe_ingredient_id'), table_name='recipe_ingredient_provenance')
    op.drop_table('recipe_ingredient_provenance')
    op.drop_index(op.f('ix_meal_plan_template_entries_template_id'), table_name='meal_plan_template_entries')
    op.drop_table('meal_plan_template_entries')
    op.drop_index(op.f('ix_diary_meal_template_items_template_id'), table_name='diary_meal_template_items')
    op.drop_table('diary_meal_template_items')
    op.drop_index(op.f('ix_weight_logs_user_id'), table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_profile_id'), table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_log_date'), table_name='weight_logs')
    op.drop_table('weight_logs')
    op.drop_index(op.f('ix_saved_filter_presets_user_id'), table_name='saved_filter_presets')
    op.drop_index(op.f('ix_saved_filter_presets_profile_id'), table_name='saved_filter_presets')
    op.drop_table('saved_filter_presets')
    op.drop_index('uq_robustness_results_recipe_id_latest', table_name='robustness_results', postgresql_where=sa.text('is_latest'), sqlite_where=sa.text('is_latest'))
    op.drop_index('ix_robustness_results_recipe_id_is_latest', table_name='robustness_results')
    op.drop_index(op.f('ix_robustness_results_recipe_id'), table_name='robustness_results')
    op.drop_table('robustness_results')
    op.drop_index(op.f('ix_recipe_tags_tag'), table_name='recipe_tags')
    op.drop_index(op.f('ix_recipe_tags_recipe_id'), table_name='recipe_tags')
    op.drop_table('recipe_tags')
    op.drop_index(op.f('ix_recipe_shares_shared_with_user_id'), table_name='recipe_shares')
    op.drop_index(op.f('ix_recipe_shares_recipe_id'), table_name='recipe_shares')
    op.drop_table('recipe_shares')
    op.drop_index(op.f('ix_recipe_ratings_user_id'), table_name='recipe_ratings')
    op.drop_index(op.f('ix_recipe_ratings_recipe_id'), table_name='recipe_ratings')
    op.drop_table('recipe_ratings')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_recipe_comments_user_id'), table_name='recipe_comments')
    op.drop_index(op.f('ix_recipe_comments_recipe_id'), table_name='recipe_comments')
    op.drop_table('recipe_comments')
    op.drop_index(op.f('ix_medical_recommendation_acknowledgements_profile_id'), table_name='medical_recommendation_acknowledgements')
    op.drop_table('medical_recommendation_acknowledgements')
    op.drop_index(op.f('ix_meal_plan_templates_user_id'), table_name='meal_plan_templates')
    op.drop_index(op.f('ix_meal_plan_templates_profile_id'), table_name='meal_plan_templates')
    op.drop_table('meal_plan_templates')
    op.drop_index(op.f('ix_meal_plan_entries_user_id'), table_name='meal_plan_entries')
    op.drop_index(op.f('ix_meal_plan_entries_profile_id'), table_name='meal_plan_entries')
    op.drop_index(op.f('ix_meal_plan_entries_plan_date'), table_name='meal_plan_entries')
    op.drop_table('meal_plan_entries')
    op.drop_index(op.f('ix_dietary_constraints_user_id'), table_name='dietary_constraints')
    op.drop_index(op.f('ix_dietary_constraints_profile_id'), table_name='dietary_constraints')
    op.drop_table('dietary_constraints')
    op.drop_index(op.f('ix_diary_snapshots_user_id'), table_name='diary_snapshots')
    op.drop_index(op.f('ix_diary_snapshots_profile_id'), table_name='diary_snapshots')
    op.drop_index(op.f('ix_diary_snapshots_entry_date'), table_name='diary_snapshots')
    op.drop_table('diary_snapshots')
    op.drop_index(op.f('ix_diary_meal_templates_user_id'), table_name='diary_meal_templates')
    op.drop_index(op.f('ix_diary_meal_templates_profile_id'), table_name='diary_meal_templates')
    op.drop_table('diary_meal_templates')
    op.drop_index(op.f('ix_diary_entries_user_id'), table_name='diary_entries')
    op.drop_index(op.f('ix_diary_entries_profile_id'), table_name='diary_entries')
    op.drop_index(op.f('ix_diary_entries_entry_date'), table_name='diary_entries')
    op.drop_table('diary_entries')
    op.drop_index(op.f('ix_collection_recipes_recipe_id'), table_name='collection_recipes')
    op.drop_index(op.f('ix_collection_recipes_collection_id'), table_name='collection_recipes')
    op.drop_table('collection_recipes')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_import_slug'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_food_prices_user_id'), table_name='food_prices')
    op.drop_index(op.f('ix_food_prices_food_id'), table_name='food_prices')
    op.drop_table('food_prices')
    op.drop_index('ix_food_nutrients_key_amount', table_name='food_nutrients')
    op.drop_index(op.f('ix_food_nutrients_food_id'), table_name='food_nutrients')
    op.drop_table('food_nutrients')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_clinician_notes_clinician_user_id'), table_name='clinician_notes')
    op.drop_index(op.f('ix_clinician_notes_client_user_id'), table_name='clinician_notes')
    op.drop_table('clinician_notes')
    op.drop_index(op.f('ix_clinician_client_links_clinician_user_id'), table_name='clinician_client_links')
    op.drop_index(op.f('ix_clinician_client_links_client_user_id'), table_name='clinician_client_links')
    op.drop_table('clinician_client_links')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_foods_name_trgm', table_name='foods', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_foods_gtin_upc'), table_name='foods')
    op.drop_index(op.f('ix_foods_fdc_id'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
